package com.kami.gamelist.core.ui.localization

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    // Common
    val addedToFavorites: String,
    val removedFromFavorites: String,
    val undo: String,
    val retry: String,
    val offlineBanner: String,
    val sort: String,
    val all: String,
    val delete: String,
    val cancel: String,
    val confirm: String,
    val game: String,
    val games: String,

    // Home
    val appTitle: String,
    val freeCatalog: String,
    val genre: String,
    val platform: String,
    val releaseDate: String,
    val alphabetical: String,
    val defaultSort: String,
    val noGamesFound: String,
    val tryAdjustingFilters: String,
    val recentReleases: String,
    val popularNow: String,
    val forYou: String,

    // Detail
    val screenshots: String,
    val systemRequirements: String,
    val os: String,
    val processor: String,
    val memory: String,
    val graphics: String,
    val storage: String,
    val publisher: String,
    val developer: String,
    val release: String,

    // Search
    val searchForGames: String,
    val findGamesByName: String,
    val searchPlaceholder: String,
    val noResults: String,
    val tryDifferentTerm: String,

    // Favorites
    val favorites: String,
    val noFavoritesYet: String,
    val tapHeartToAdd: String,
    val sortRecent: String,
    val sortAZ: String,

    // Lists
    val myLists: String,
    val noListsYet: String,
    val createListToOrganize: String,
    val newList: String,
    val listName: String,
    val create: String,
    val deleteList: String,
    val noGamesYet: String,
    val browseToAdd: String,
    val browseGames: String,
    val addToList: String,
    val sortNewest: String,
    val sortMostGames: String,

    // Settings
    val settings: String,
    val appearance: String,
    val theme: String,
    val chooseAppearance: String,
    val accentColor: String,
    val primaryColorDesc: String,
    val gridLayout: String,
    val gameCardColumns: String,
    val language: String,
    val appLanguage: String,
    val data: String,
    val clearGameCache: String,
    val clearGameCacheDesc: String,
    val clearSearchHistory: String,
    val clearSearchHistoryDesc: String,
    val resetOnboarding: String,
    val resetOnboardingDesc: String,
    val onboardingWillShow: String,
    val preferences: String,
    val favoriteGenres: String,
    val usedForRecommendations: String,
    val filterByPlatform: String,
    val about: String,
    val aboutDescription: String,
    val themeDark: String,
    val themeLight: String,
    val themeSystem: String,
    val gridAuto: String,
    val gridTwoCol: String,
    val gridThreeCol: String,
    val accentUpdated: String,
    val gameCacheCleared: String,
    val searchHistoryCleared: String,

    // Settings - Dialogs
    val clearCacheQuestion: String,
    val clearCacheMessage: String,
    val clearHistoryQuestion: String,
    val clearHistoryMessage: String,

    // Onboarding
    val welcomeSubtitle: String,
    val featureBrowse: String,
    val featureBrowseDesc: String,
    val featureFilter: String,
    val featureFilterDesc: String,
    val featureFavorite: String,
    val featureFavoriteDesc: String,
    val featureSearch: String,
    val featureSearchDesc: String,
    val continueButton: String,
    val customizeFeed: String,
    val pickGenres: String,
    val preferredPlatform: String,
    val getStarted: String,
    val changeInSettings: String,

    // Default lists
    val listPlaying: String,
    val listWantToPlay: String,
    val listPlayed: String,

    // Platform preferences
    val platformAll: String,
    val platformPC: String,
    val platformBrowser: String,

    // Gate
    val updateRequiredTitle: String,
    val updateRequiredMessage: String,
    val updateNow: String,
    val maintenanceTitle: String,
    val maintenanceDefaultMessage: String,
    val updateAvailableTitle: String,
    val updateAvailableMessage: String,
    val later: String,
    val whatsNew: String,
) {
    fun freeToPlayCount(count: Int) = "$count $freeCatalog"
    fun favoritesCount(count: Int) = "$favorites ($count)"
    fun myListsCount(count: Int) = "$myLists ($count)"
    fun listCreated(name: String) = "\"$name\" ${createdLabel}"
    fun listDeleted(name: String) = "\"$name\" ${deletedLabel}"
    fun deleteListQuestion(name: String) = "$delete \"$name\"?"
    fun deleteListMessage() = deleteListConfirmMessage
    fun deleteConfirmMessage(name: String) = "$deleteListAreYouSure \"$name\"?\n$deleteListCannotUndo"
    fun gameCountLabel(count: Int) = if (count == 1) "$count $game" else "$count $games"

    internal val createdLabel: String get() = if (this === En) "created" else "criada"
    internal val deletedLabel: String get() = if (this === En) "deleted" else "excluída"
    internal val deleteListConfirmMessage: String get() = if (this === En) "This list and its game references will be removed." else "Esta lista e suas referências de jogos serão removidas."
    internal val deleteListAreYouSure: String get() = if (this === En) "Are you sure you want to delete" else "Tem certeza que deseja excluir"
    internal val deleteListCannotUndo: String get() = if (this === En) "This action cannot be undone." else "Esta ação não pode ser desfeita."

    companion object {
        val En = AppStrings(
            addedToFavorites = "Added to favorites",
            removedFromFavorites = "Removed from favorites",
            undo = "Undo",
            retry = "RETRY",
            offlineBanner = "OFFLINE — SHOWING CACHED DATA",
            sort = "SORT",
            all = "All",
            delete = "Delete",
            cancel = "Cancel",
            confirm = "Confirm",
            game = "game",
            games = "games",

            appTitle = "LevelUp Hub",
            freeCatalog = "free-to-play games",
            genre = "GENRE",
            platform = "PLATFORM",
            releaseDate = "Release Date",
            alphabetical = "A-Z",
            defaultSort = "Default",
            noGamesFound = "No games found",
            tryAdjustingFilters = "Try adjusting your filters",
            recentReleases = "Recent Releases",
            popularNow = "Popular Now",
            forYou = "For You",

            screenshots = "Screenshots",
            systemRequirements = "System Requirements",
            os = "OS",
            processor = "Processor",
            memory = "Memory",
            graphics = "Graphics",
            storage = "Storage",
            publisher = "Publisher",
            developer = "Developer",
            release = "Release",

            searchForGames = "Search for games",
            findGamesByName = "Find free-to-play games by name",
            searchPlaceholder = "Search games...",
            noResults = "No results",
            tryDifferentTerm = "Try a different search term",

            favorites = "Favorites",
            noFavoritesYet = "No favorites yet",
            tapHeartToAdd = "Tap the heart on a game to add it here",
            sortRecent = "Recent",
            sortAZ = "A-Z",

            myLists = "My Lists",
            noListsYet = "No lists yet",
            createListToOrganize = "Create a list to organize your games",
            newList = "NEW LIST",
            listName = "List name",
            create = "CREATE",
            deleteList = "DELETE LIST",
            noGamesYet = "No games yet",
            browseToAdd = "Browse the catalog and tap the list icon on a game's detail screen to add it here",
            browseGames = "Browse Games",
            addToList = "ADD TO LIST",
            sortNewest = "Newest",
            sortMostGames = "Most Games",

            settings = "Settings",
            appearance = "APPEARANCE",
            theme = "Theme",
            chooseAppearance = "Choose app appearance",
            accentColor = "Accent color",
            primaryColorDesc = "Primary color across the app",
            gridLayout = "Grid layout",
            gameCardColumns = "Game card columns",
            language = "Language",
            appLanguage = "App display language",
            data = "DATA",
            clearGameCache = "Clear game cache",
            clearGameCacheDesc = "Forces re-download of game data on next visit",
            clearSearchHistory = "Clear search history",
            clearSearchHistoryDesc = "Removes all recent search queries",
            resetOnboarding = "Reset onboarding",
            resetOnboardingDesc = "Show the welcome screen again on next launch",
            onboardingWillShow = "Onboarding will show on next launch",
            preferences = "PREFERENCES",
            favoriteGenres = "Favorite genres",
            usedForRecommendations = "Used for recommendations",
            filterByPlatform = "Filter games by platform",
            about = "ABOUT",
            aboutDescription = "v1.0.0 — LevelUp Hub — Free-to-Play game catalog powered by FreeToGame API",
            themeDark = "Dark",
            themeLight = "Light",
            themeSystem = "System",
            gridAuto = "Auto",
            gridTwoCol = "2 Col",
            gridThreeCol = "3 Col",
            accentUpdated = "Accent color updated",
            gameCacheCleared = "Game cache cleared",
            searchHistoryCleared = "Search history cleared",

            clearCacheQuestion = "Clear game cache?",
            clearCacheMessage = "Game data will be re-downloaded on next visit.",
            clearHistoryQuestion = "Clear search history?",
            clearHistoryMessage = "All recent searches will be removed.",

            welcomeSubtitle = "Your free-to-play game catalog",
            featureBrowse = "Browse",
            featureBrowseDesc = "Explore hundreds of free-to-play games",
            featureFilter = "Filter",
            featureFilterDesc = "Find games by genre and platform",
            featureFavorite = "Favorite",
            featureFavoriteDesc = "Tap the heart on any card to save it",
            featureSearch = "Search",
            featureSearchDesc = "Quickly find any game by name",
            continueButton = "Continue",
            customizeFeed = "Customize Your Feed",
            pickGenres = "Pick genres you enjoy",
            preferredPlatform = "Preferred Platform",
            getStarted = "Get Started",
            changeInSettings = "You can change these in Settings",

            listPlaying = "Playing",
            listWantToPlay = "Want to Play",
            listPlayed = "Played",

            platformAll = "All",
            platformPC = "PC",
            platformBrowser = "Browser",

            updateRequiredTitle = "Update required",
            updateRequiredMessage = "This version is no longer supported. Update to keep playing.",
            updateNow = "Update Now",
            maintenanceTitle = "Under maintenance",
            maintenanceDefaultMessage = "We'll be back shortly. Thanks for your patience.",
            updateAvailableTitle = "Update available",
            updateAvailableMessage = "A new version is ready.",
            later = "Later",
            whatsNew = "What's New",
        )

        val PtBr = AppStrings(
            addedToFavorites = "Adicionado aos favoritos",
            removedFromFavorites = "Removido dos favoritos",
            undo = "Desfazer",
            retry = "TENTAR NOVAMENTE",
            offlineBanner = "OFFLINE — EXIBINDO DADOS EM CACHE",
            sort = "ORDENAR",
            all = "Todos",
            delete = "Excluir",
            cancel = "Cancelar",
            confirm = "Confirmar",
            game = "jogo",
            games = "jogos",

            appTitle = "LevelUp Hub",
            freeCatalog = "jogos gratuitos",
            genre = "GÊNERO",
            platform = "PLATAFORMA",
            releaseDate = "Lançamento",
            alphabetical = "A-Z",
            defaultSort = "Padrão",
            noGamesFound = "Nenhum jogo encontrado",
            tryAdjustingFilters = "Tente ajustar seus filtros",
            recentReleases = "Lançamentos Recentes",
            popularNow = "Populares Agora",
            forYou = "Para Você",

            screenshots = "Capturas de Tela",
            systemRequirements = "Requisitos do Sistema",
            os = "SO",
            processor = "Processador",
            memory = "Memória",
            graphics = "Gráficos",
            storage = "Armazenamento",
            publisher = "Publicadora",
            developer = "Desenvolvedora",
            release = "Lançamento",

            searchForGames = "Pesquisar jogos",
            findGamesByName = "Encontre jogos gratuitos pelo nome",
            searchPlaceholder = "Pesquisar jogos...",
            noResults = "Sem resultados",
            tryDifferentTerm = "Tente um termo diferente",

            favorites = "Favoritos",
            noFavoritesYet = "Nenhum favorito ainda",
            tapHeartToAdd = "Toque no coração em um jogo para adicioná-lo aqui",
            sortRecent = "Recentes",
            sortAZ = "A-Z",

            myLists = "Minhas Listas",
            noListsYet = "Nenhuma lista ainda",
            createListToOrganize = "Crie uma lista para organizar seus jogos",
            newList = "NOVA LISTA",
            listName = "Nome da lista",
            create = "CRIAR",
            deleteList = "EXCLUIR LISTA",
            noGamesYet = "Nenhum jogo ainda",
            browseToAdd = "Navegue pelo catálogo e toque no ícone de lista na tela de detalhes de um jogo para adicioná-lo aqui",
            browseGames = "Explorar Jogos",
            addToList = "ADICIONAR À LISTA",
            sortNewest = "Mais Recentes",
            sortMostGames = "Mais Jogos",

            settings = "Configurações",
            appearance = "APARÊNCIA",
            theme = "Tema",
            chooseAppearance = "Escolha a aparência do app",
            accentColor = "Cor de destaque",
            primaryColorDesc = "Cor principal do app",
            gridLayout = "Layout da grade",
            gameCardColumns = "Colunas dos cards de jogos",
            language = "Idioma",
            appLanguage = "Idioma de exibição do app",
            data = "DADOS",
            clearGameCache = "Limpar cache de jogos",
            clearGameCacheDesc = "Força o download dos dados dos jogos na próxima visita",
            clearSearchHistory = "Limpar histórico de busca",
            clearSearchHistoryDesc = "Remove todas as buscas recentes",
            resetOnboarding = "Redefinir introdução",
            resetOnboardingDesc = "Mostrar a tela de boas-vindas novamente na próxima abertura",
            onboardingWillShow = "A introdução será exibida na próxima abertura",
            preferences = "PREFERÊNCIAS",
            favoriteGenres = "Gêneros favoritos",
            usedForRecommendations = "Usado para recomendações",
            filterByPlatform = "Filtrar jogos por plataforma",
            about = "SOBRE",
            aboutDescription = "v1.0.0 — LevelUp Hub — Catálogo de jogos gratuitos com a API FreeToGame",
            themeDark = "Escuro",
            themeLight = "Claro",
            themeSystem = "Sistema",
            gridAuto = "Auto",
            gridTwoCol = "2 Col",
            gridThreeCol = "3 Col",
            accentUpdated = "Cor de destaque atualizada",
            gameCacheCleared = "Cache de jogos limpo",
            searchHistoryCleared = "Histórico de busca limpo",

            clearCacheQuestion = "Limpar cache de jogos?",
            clearCacheMessage = "Os dados dos jogos serão baixados novamente na próxima visita.",
            clearHistoryQuestion = "Limpar histórico de busca?",
            clearHistoryMessage = "Todas as buscas recentes serão removidas.",

            welcomeSubtitle = "Seu catálogo de jogos gratuitos",
            featureBrowse = "Explorar",
            featureBrowseDesc = "Explore centenas de jogos gratuitos",
            featureFilter = "Filtrar",
            featureFilterDesc = "Encontre jogos por gênero e plataforma",
            featureFavorite = "Favoritar",
            featureFavoriteDesc = "Toque no coração em qualquer card para salvar",
            featureSearch = "Pesquisar",
            featureSearchDesc = "Encontre qualquer jogo pelo nome rapidamente",
            continueButton = "Continuar",
            customizeFeed = "Personalize Seu Feed",
            pickGenres = "Escolha gêneros que você curte",
            preferredPlatform = "Plataforma Preferida",
            getStarted = "Começar",
            changeInSettings = "Você pode alterar isso nas Configurações",

            listPlaying = "Jogando",
            listWantToPlay = "Quero Jogar",
            listPlayed = "Jogados",

            platformAll = "Todos",
            platformPC = "PC",
            platformBrowser = "Navegador",

            updateRequiredTitle = "Atualização necessária",
            updateRequiredMessage = "Esta versão não é mais suportada. Atualize para continuar jogando.",
            updateNow = "Atualizar agora",
            maintenanceTitle = "Em manutenção",
            maintenanceDefaultMessage = "Voltamos em breve. Obrigado pela paciência.",
            updateAvailableTitle = "Atualização disponível",
            updateAvailableMessage = "Uma nova versão está pronta.",
            later = "Depois",
            whatsNew = "Novidades",
        )
    }
}

val LocalStrings = staticCompositionLocalOf { AppStrings.En }
